# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java:
          - {
            name: "One"
          }
          - {
            name: "Two",
            mvn-version: "3.8.5"
          }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: List images
        run: docker image ls
      - name: Show free space
        run: df -h
      - name: dotnet consumption
        run: du -hs /usr/share/dotnet
      - name: swift consumption
        run: du -hs /usr/share/swift
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Switch Maven version
        if: "matrix.java.mvn-version != ''"
        run: echo 'distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${{matrix.java.mvn-version}}/apache-maven-${{matrix.java.mvn-version}}-bin.zip' >> .mvn/wrapper/maven-wrapper.properties

      - name: Cat
        run: cat .mvn/wrapper/maven-wrapper.properties
